# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  schedule:
    - cron: "30 5,17 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - uses: actions/setup-node
      with:
        node-version: '16'
    - run: npm install
    - run: npm run update-readme
      env:
        RAPIDAPI_API_KEY: ${{ secrets.RAPIDAPI_API_KEY }}
    - run: |
        git config user.name idkan
        git config user.email abraham.serena.lk@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
        git push origin main
